version: "1.0"

#############################
# Owner: Bahaeddine FERIANI #
#############################

services:
  namenode:
    image: master
    container_name: namenode
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - DAEMON=namenode
    networks:
      - kepler

volumes:
  hadoop_namenode:
networks:
  kepler:
    name: kepler
    driver: bridge
