version: "1.0"

#############################
# Owner: Bahaeddine FERIANI #
#############################

services:
  datanode:
    image: slave
    container_name: datanode2
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      - DAEMON=datanode
    networks:
      - kepler


volumes:
  hadoop_datanode:
networks:
  kepler:
    name: kepler
    driver: bridge
